version: "3"
services: 
  web:
    image: kckc/beexp
    ports:
      - "3333:3000"
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6666:6379"
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet:
