version: "3"
services: 
  web:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - webnet
  redis-commander:
    image: tenstartups/redis-commander
    command: "--redis-host redis"
    ports:
      - "8081:8081"
    networks:
      - webnet
networks:
  webnet:
